### ISSUE TITLE
Is this correct to use a linear layer to do classifaction?

### ISSUE THREAD

**Issue by haozewu** [ShayanPersonal/stacked-autoencoder-pytorch#3]
Please look at the code in this place:

https://github.com/ShayanPersonal/stacked-autoencoder-pytorch/blob/1b0d6043750951e59d5380ea70d8afcad6e02f9d/run.py#L39

If I don't misunderstand, this SAE just run finished and the dim of SAE output is just same with the input, then use a linear layer to do classification, the process of classification don't use SAE at all.

The right process should be using half of SAE( might be the lowest dim in the middle layer of SAE) to decrease dim to the number of classification dim, then use CEloss to do classification.

If anyone uses this code, what about your result?

**Comment by ShayanPersonal** [comment]
The classifier is used to test the quality of the features obtained by the autoencoder and is trained independent of the autoencoder. In training mode, the autoencoder returns the feature map output by the deepest layer. In test mode, it also returns a reconstruction. The gradient updates for the autoencoder aren't performed in run.py, rather it's performed by the model itself in model.py. Each layer independently performs a gradient update to get closer to reconstructing its input from the layer above.

https://github.com/ShayanPersonal/stacked-autoencoder-pytorch/blob/1b0d6043750951e59d5380ea70d8afcad6e02f9d/run.py#L50-L51

https://github.com/ShayanPersonal/stacked-autoencoder-pytorch/blob/1b0d6043750951e59d5380ea70d8afcad6e02f9d/model.py#L32-L46
